### ISSUE TITLE
Added methods cause error when swizzling if the new class is a Swift class

### ISSUE THREAD

**Issue by kuglee** [alexzielenski/ZKSwizzle#4]
I try to swizzle an Objective-C class with a Swift 3.0 class. It's an Objective-C project and I added a Swift file to it. The swizzling works, the implemented methods successfully replaced the originals.
However when I call a method that isn't present in the original class I get a  EXC_BAD_ACCESS  error.
This occurs even when I swizzle a Swift class with an another Swift class.

In the example below when bar() is called an EXC_BAD_ACCESS  error occurs.

The main.m file:
```Objective-c
#import <Foundation/Foundation.h>
#import "FooBar-Swift.h"
#import "ZKSwizzle.h"

@interface FooObjc : NSObject
- (void)foo:(id)arg1;
@end

@implementation FooObjc
- (void)foo:(id)arg1 {
    NSLog(@"fooObjc");
}
@end

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        BOOL didSwizzle = ZKSwizzle(FooBar.FooSwift, FooObjc);  // Swift class name should be written as ProjectName.ClassName
        if (didSwizzle)
            NSLog(@"Swizzle OK!");
        else
            NSLog(@"Could not swizzle!");

        FooObjc *obj = [[FooObjc alloc] init];
        [obj foo: obj];
    }
    return 0;
}
```

The FooSwift.swift file:
```Swift
import Foundation

class FooSwift : NSObject {  // Inherit from NSObject for swizzling to work
    func bar() {
        NSLog("barSwift")
    }
    
    func foo(_ arg1:Any) {  // First parameter label should be optional to avoid Objective-c renaming
        NSLog("fooSwift")
        bar()   // <-- EXC_BAD_ACCESS error
    }
}
```

**Comment by alexzielenski** [comment]
I think the problem is that the Swift compiler is dynamically dispatching bar(), which is not a member of FooObjc or detectable from the runtime. Try adding the "dynamic" keyword before `func bar()` and see how far that gets you.

**Comment by kuglee** [comment]
Thank you! It's working with "dynamic" or "private".
It turned out to be a visibility issue.
